version: '3.7'

services:
  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/

  web:
    build: backend
    volumes:
      - ./backend:/usr/src/app/
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: "development"
      FLASK_APP: "app.py"
    command: flask run --host=0.0.0.0 --cert=adhoc

  frontend:
    build: frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    links:
      - web
    command: yarn start

volumes:
  pgdata:
